#!/usr/bin/env bash
source "$(dirname "$0")/_common.sh"

PORTAL='^(TestReceiveUploadSurvivesAbruptPortalRestart|TestReceiveUploadContinuesAcrossPortalRouteAddresses|TestReceiveUploadSerializesSameOffsetAcrossPortalRoutes|TestSharedFileRangeContinuesAcrossPortalRouteAddresses|TestManagedReceiveStartsAfterInterruptedLargeRecovery|TestManagedReceiveContinuesSameManifestFromVerifiedPhysicalPartial|TestManagedReceiveHandsOffFromWifiToUSBWithoutRestarting|TestManagedReceiveRejectsChangedSourceAndPartialRace|TestAdoptReceivePartialFreezesVerifiedWirelessCheckpointForUSB|TestManagedReceiveUsesBoundedUSBCheckpointProof|TestFastWebRTCDownloadResumesFromStoredOffset)$'
DAEMON='^(TestAutomaticRecoveryRunsOnlyAfterSourceDisappearsAndReturns|TestPersistedReconnectStateRecoversAfterDaemonRestart|TestAutomaticUploadRecoveryRunsAfterDestinationReconnect|TestManagedUploadRetriesAndCompletesAfterStaleMountReconnect|TestLargeOrdinaryWifiUploadAdoptsCheckpointIntoManagedUSBRecovery|TestOrdinaryWifiUploadAdoptsVerifiedCheckpointIntoManagedUSBRecovery)$'
RECOVERY='^(TestLaptopToPhoneRecoveryResumesExistingPartialByVerifiedAppend|TestLaptopToPhoneRecoveryContinuesUnstartedManifestEntries|TestLaptopToPhoneRecoveryAcceptsAlreadyCompleteDestinationWithoutAppendProbe|TestLaptopToPhoneRecoveryContinuesAllFilesByVerifiedAppend|TestManagedUploadRecoveryPersistsProgressAndCompletion|TestManagedDownloadRecoveryPersistsProgressAndCompletion|TestManagedRecoveryRejectsChangedExplicitWirelessCandidateBeforeUSBAdoption)$'

run_timeout 240 "portal reconnect and transport handoff" go test -count=1 ./internal/portal -run "$PORTAL" -v
run_timeout 240 "daemon disconnect/reconnect" go test -count=1 ./internal/daemon -run "$DAEMON" -v
run_timeout 240 "USB recovery continuity" go test -count=1 ./internal/recovery -run "$RECOVERY" -v

printf '\nRECONNECT/HANDOFF BATCH: PASS\n'
